export const langageOptions = [{
    label: "Afrikaans",
    value:  "af-ZA",
}, {
    label: "Arabic",
    value: "ar-DZ",
}, {
    label: "Basque",
    value: "eu-ES",
}, {
    label: "Bulgarian",
    value: "bg-BG",
}, {
    label: "Catalan",
    value: "ca-ES",
}, {
    label: "Chinese ,darin",
    value: "cmn-Hans-CN",
}, {
    label: "Chinese ,tonese",
    value: "yue-Hant-HK",
}, {
    label: "Croatian",
    value: "hr_HR",
}, {
    label: "Czech",
    value: "cs-CZ",
}, {
    label: "Danish",
    value: "da-DK",
}, {
    label: "English",
    value: "en-US",
}, {
    label: "Farsi",
    value: "fa-IR",
}, {
    label: "French",
    value: "fr-FR",
}, {
    label: "Filipino",
    value: "fil-PH",
}, {
    label: "Galician",
    value: "gl-ES",
}, {
    label: "German",
    value: "de-DE",
}, {
    label: "Greek",
    value: "el-GR",
}, {
    label: "Finnish",
    value: "fi-FI",
}, {
    label: "Hebrew",
    value: "he-IL",
}, {
    label: "Hindi",
    value: "hi-IN",
}, {
    label: "Hungarian",
    value: "hu-HU",
}, {
    label: "Indonesian",
    value: "id-ID",
}, {
    label: "Icelandic",
    value: "is-IS",
}, {
    label: "Italian",
    value: "it-IT",
}, {
    label: "Japanese",
    value: "ja-JP",
}, {
    label: "Korean",
    value: "ko-KR",
}, {
    label: "Lithuanian",
    value: "lt-LT",
}, {
    label: "Malaysian",
    value: "ms-MY",
}, {
    label: "Dutch",
    value: "nl-NL",
}, {
    label: "Norwegian",
    value: "nb-NO",
}, {
    label: "Polish",
    value: "pl-PL",
}, {
    label: "Portuguese",
    value: "pt-BR",
    value: "pt-PT",
}, {
    label: "Romanian",
    value: "ro-RO",
}, {
    label: "Russian",
    value: "ru-RU",
}, {
    label: "Serbian",
    value: "sr-RS",
}, {
    label: "Slovak",
    value: "sk-SK",
}, {
    label: "Slovenian",
    value: "sl-SI",
}, {
    label: "Spanish",
    value: "es-ES",
}, {
    label: "Swedish",
    value: "sv-SE",
}, {
    label: "Thai",
    value: "th-TH",
}, {
    label: "Turkish",
    value: "tr-TR",
}, {
    label: "Ukrainian",
    value: "uk-UA",
}, {
    label: "Vietnamese",
    value: "vi-VN",
}, {
    label: "Zulu",
    value: "zu-ZA",
}];
